name: Deploy UI Production

on:
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.event.release.tag_name, 'production_backend')
    uses: ./.github/workflows/reusableBuild.yml
    secrets: inherit
    with:
      environment: "production"
