export const PRODUCT_TIER_STANDARD = 'Standard';
export const PRODUCT_TIER_FREE = 'Free';


export const SUBSCRIPTION_STATUS_TRIAL = 'TRIAL';
export const SUBSCRIPTION_STATUS_ACTIVE = 'ACTIVE';
export const SUBSCRIPTION_STATUS_CANCELED = 'CANCELED';