/**
 * Converts a linear array into an object
 * consisting of keys generated by the selector function
 * and values of all items that have the same key via
 * the selector function
 * @param data the array to split
 * @param keyGenerator the function that generates a key from an item
 */
export function arrayToMappedSubArrays(data, keyGenerator){
  const map = {};
  data.forEach((item)=> {
    const key = keyGenerator(item);
    if (map[key]){
      map[key].push(item);
    } else {
      map[key] = [item];
    }
  });
  return map;
}